version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=experiments
    ports:
      - "32768:32768"
